export enum ActionType {
  Empty,
  ChangeIsLoading,
  ChangeHamButton,
  ChangeMapType,
  ChangeCivil,
  ChangeNoWood,
  ChangeTheme,
  ChangeMiniMap,
  RotateMap,
  ChangeOperation,
  ResetCouter,
  ChangeCounter,
  PlaceOrDeleteBuilding,
  SetCopiedBuilding,
}
