import { BuildingColor } from './building-color';

export const BuildingPersian = {
  防: ['消', '维', '治', '医疗'],
  防护: ['消防局', '维修站', '治安厅', '医疗站'],
  普通住宅需求: {
    商业: [
      '粮食货摊',
      '蔬菜货摊',
      '水果货摊',
      '生肉货摊',
      '鱼虾货摊',
      '瓷器货摊',
      '香料货摊',
      '地毯货摊',
    ],
    市政: ['饮水台', '办公厅'],
    文化: ['斗兽场'],
    宗教: ['礼拜堂', '小清真寺'],
  },
  高级住宅需求: {
    商业: [
      '粮食货摊',
      '蔬菜货摊',
      '水果货摊',
      '生肉货摊',
      '鱼虾货摊',
      '瓷器货摊',
      '香料货摊',
      '地毯货摊',
      '糖品货摊',
      '烟草货摊',
      '芝麻油货摊',
      '葡萄酒货摊',
    ],
    市政: ['饮水台', '办公厅'],
    文化: ['浴池', '斗兽场', '大学', '观星台'],
    宗教: ['小清真寺', '大清真寺'],
  },
  住宅: [
    {
      name: '普通住宅',
      text: '宅',
      size: 1,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['住宅'][0],
    },
    {
      name: '高级住宅',
      text: '别墅',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['住宅'][1],
    },
  ],
  农业: [
    {
      name: '麦田',
      text: '麦田',
      size: 3,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['农业'][0],
    },
    {
      name: '菠菜田',
      text: '菠菜田',
      size: 3,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['农业'][1],
    },
    {
      name: '椰枣园',
      text: '椰枣园',
      size: 3,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['农业'][2],
    },
    {
      name: '猎户小屋',
      text: '猎户',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['农业'][3],
    },
    {
      name: '绵阳牧场',
      text: '绵阳牧场',
      size: 3,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['农业'][4],
    },
    {
      name: '甜菜田',
      text: '甜菜田',
      size: 3,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['农业'][5],
    },
    {
      name: '烟草田',
      text: '烟草田',
      size: 3,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['农业'][6],
    },
    {
      name: '芝麻田',
      text: '芝麻田',
      size: 3,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['农业'][7],
    },
    {
      name: '葡萄园',
      text: '葡萄园',
      size: 3,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['农业'][8],
    },
  ],
  工业: [
    {
      name: '砖窑',
      text: '砖窑',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['工业'][0],
    },
    {
      name: '炼铜场',
      text: '炼铜场',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['工业'][1],
    },
    {
      name: '陶瓷场',
      text: '陶瓷场',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['工业'][2],
    },
    {
      name: '香料作坊',
      text: '香料作坊',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['工业'][3],
    },
    {
      name: '地毯作坊',
      text: '地毯作坊',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['工业'][4],
    },
    {
      name: '制糖厂',
      text: '制糖厂',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['工业'][5],
    },
    {
      name: '油坊',
      text: '油坊',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['工业'][6],
    },
    {
      name: '酒坊',
      text: '酒坊',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['工业'][7],
    },
  ],
  商业: [
    {
      name: '粮食货摊',
      text: '粮',
      size: 1,
      range: 5,
      color: BuildingColor.Black,
      background: BuildingColor['商业'][0],
    },
    {
      name: '蔬菜货摊',
      text: '菜',
      size: 1,
      range: 5,
      color: BuildingColor.Black,
      background: BuildingColor['商业'][1],
    },
    {
      name: '水果货摊',
      text: '果',
      size: 1,
      range: 5,
      color: BuildingColor.Black,
      background: BuildingColor['商业'][2],
    },
    {
      name: '生肉货摊',
      text: '肉',
      size: 1,
      range: 5,
      color: BuildingColor.Black,
      background: BuildingColor['商业'][3],
    },
    {
      name: '鱼虾货摊',
      text: '鱼',
      size: 1,
      range: 5,
      color: BuildingColor.Black,
      background: BuildingColor['商业'][4],
    },
    {
      name: '瓷器货摊',
      text: '瓷',
      size: 1,
      range: 5,
      color: BuildingColor.Black,
      background: BuildingColor['商业'][5],
    },
    {
      name: '香料货摊',
      text: '香',
      size: 1,
      range: 5,
      color: BuildingColor.Black,
      background: BuildingColor['商业'][6],
    },
    {
      name: '地毯货摊',
      text: '毯',
      size: 1,
      range: 5,
      color: BuildingColor.Black,
      background: BuildingColor['商业'][7],
    },
    {
      name: '糖品货摊',
      text: '糖',
      size: 1,
      range: 5,
      color: BuildingColor.Black,
      background: BuildingColor['商业'][8],
    },
    {
      name: '烟草货摊',
      text: '烟',
      size: 1,
      range: 5,
      color: BuildingColor.Black,
      background: BuildingColor['商业'][9],
    },
    {
      name: '芝麻油货摊',
      text: '油',
      size: 1,
      range: 5,
      color: BuildingColor.Black,
      background: BuildingColor['商业'][10],
    },
    {
      name: '葡萄酒货摊',
      text: '酒',
      size: 1,
      range: 5,
      color: BuildingColor.Black,
      background: BuildingColor['商业'][11],
    },
  ],
  市政: [
    {
      name: '饮水台',
      text: '水',
      size: 1,
      range: 4,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['水'],
    },
    {
      name: '消防局',
      text: '消',
      size: 1,
      range: 6,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['防'],
    },
    {
      name: '维修站',
      text: '维',
      size: 1,
      range: 6,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['防'],
    },
    {
      name: '治安厅',
      text: '治',
      size: 1,
      range: 6,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['防'],
    },
    {
      name: '医疗站',
      text: '医疗',
      size: 2,
      range: 7,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['防'],
    },
    {
      name: '粮仓',
      text: '粮仓',
      size: 3,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['粮'],
    },
    {
      name: '货栈',
      text: '货栈',
      size: 4,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['货'],
    },
    {
      name: '宫殿',
      text: '宫殿',
      size: 4,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['殿'],
      isPalace: true,
    },
    {
      name: '办公厅',
      text: '办公厅',
      size: 2,
      range: 6,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['职'],
    },
    {
      name: '贸易站',
      text: '贸易站',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['贸'],
    },
    {
      name: '税务局',
      text: '税',
      size: 1,
      range: 4,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['税'],
    },
    {
      name: '磨坊',
      text: '磨坊',
      size: 1,
      range: 4,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['磨'],
    },
    {
      name: '水车房',
      text: '水车房',
      size: 2,
      range: 4,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['浇'],
    },
    {
      name: '驿站',
      text: '驿站',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['市政']['驿'],
    },
  ],
  文化: [
    {
      name: '浴池',
      text: '浴池',
      size: 2,
      range: 8,
      color: BuildingColor.Black,
      background: BuildingColor['文化'][0],
    },
    {
      name: '斗兽场',
      text: '斗兽场',
      size: 4,
      range: 8,
      color: BuildingColor.Black,
      background: BuildingColor['文化'][1],
    },
    {
      name: '大学',
      text: '大学',
      size: 3,
      range: 8,
      color: BuildingColor.Black,
      background: BuildingColor['文化'][2],
    },
    {
      name: '观星台',
      text: '观星台',
      size: 3,
      range: 8,
      color: BuildingColor.Black,
      background: BuildingColor['文化'][3],
    },
  ],
  宗教: [
    {
      name: '礼拜堂',
      text: '礼',
      size: 1,
      range: 6,
      color: BuildingColor.Black,
      background: BuildingColor['宗教'][0],
    },
    {
      name: '小清真寺',
      text: '小清真',
      size: 2,
      range: 8,
      color: BuildingColor.Black,
      background: BuildingColor['宗教'][1],
    },
    {
      name: '大清真寺',
      text: '大清真寺',
      size: 4,
      range: 10,
      color: BuildingColor.Black,
      background: BuildingColor['宗教'][2],
    },
  ],
  军事: [
    {
      name: '步兵兵营',
      text: '步兵',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['军事'][0],
    },
    {
      name: '射手兵营',
      text: '射手',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['军事'][1],
    },
    {
      name: '骑兵兵营',
      text: '骑兵',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['军事'][2],
    },
    {
      name: '军事学院',
      text: '军事',
      size: 3,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['军事'][3],
    },
    {
      name: '武器铺',
      text: '武器铺',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['军事'][4],
    },
    {
      name: '马厩',
      text: '马厩',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['军事'][5],
    },
    {
      name: '象棚',
      text: '象棚',
      size: 3,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['军事'][6],
    },
  ],
  美化: [
    {
      name: '树',
      text: '树',
      size: 1,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['美化']['树'],
    },
  ],
  奇迹: [
    {
      name: '通天塔',
      text: '通天塔',
      size: 6,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['奇迹'][0],
    },
    {
      name: '空中花园',
      text: '空中花园',
      size: 10,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['奇迹'][1],
    },
  ],
  通用: [
    {
      name: '2x2建筑',
      text: '2x2',
      size: 2,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['通用'][0],
    },
    {
      name: '3x3建筑',
      text: '3x3',
      size: 3,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['通用'][1],
    },
    {
      name: '4x4建筑',
      text: '4x4',
      size: 4,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['通用'][2],
    },
    {
      name: '5x5建筑',
      text: '5x5',
      size: 5,
      range: 0,
      color: BuildingColor.Black,
      background: BuildingColor['通用'][3],
    },
  ],
};
