import { BuildingColor } from './building-color';

export const BuildingGreece = {
  防: ['消', '维', '瞭', '诊所'],
  防护: ['消防局', '维修所', '瞭望台', '诊所'],
  普通住宅需求: {
    商业: [
      '粮食货摊',
      '蔬菜货摊',
      '水果货摊',
      '生肉货摊',
      '鱼虾货摊',
      '陶器店',
      '亚麻布店',
      '酒馆',
    ],
    市政: ['喷泉', '议会厅'],
    文化: ['剧场', '露天体育场'],
    宗教: ['小神殿', '中神殿'],
  },
  高级住宅需求: {
    商业: [
      '粮食货摊',
      '蔬菜货摊',
      '水果货摊',
      '生肉货摊',
      '鱼虾货摊',
      '陶器店',
      '亚麻布店',
      '酒馆',
      '羊毛货摊',
      '奶酪货摊',
      '橄榄油货摊',
    ],
    市政: ['喷泉', '议会厅'],
    文化: ['剧场', '露天体育场', '大学', '图书馆'],
    宗教: ['中神殿', '大神殿'],
  },
  住宅: [
    {
      name: '普通住宅',
      text: '宅',
      size: 1,
      range: 0,
      background: BuildingColor['住宅'][0],
    },
    {
      name: '高级住宅',
      text: '高宅',
      size: 2,
      range: 0,
      background: BuildingColor['住宅'][1],
    },
  ],
  农业: [
    {
      name: '麦田',
      text: '麦田',
      size: 2,
      range: 0,
      background: BuildingColor['农业'][0],
    },
    {
      name: '卷心菜小屋',
      text: '卷心菜',
      size: 2,
      range: 0,
      background: BuildingColor['农业'][1],
    },
    {
      name: '桔子小屋',
      text: '桔子',
      size: 2,
      range: 0,
      background: BuildingColor['农业'][2],
    },
    {
      name: '猎人小屋',
      text: '猎人',
      size: 2,
      range: 0,
      background: BuildingColor['农业'][3],
    },
    {
      name: '亚麻小屋',
      text: '亚麻',
      size: 2,
      range: 0,
      background: BuildingColor['农业'][4],
    },
    {
      name: '葡萄园',
      text: '葡萄园',
      size: 2,
      range: 0,
      background: BuildingColor['农业'][5],
    },
    {
      name: '绵羊牧场',
      text: '绵羊牧场',
      size: 3,
      range: 0,
      background: BuildingColor['农业'][6],
    },
    {
      name: '山羊牧场',
      text: '山羊牧场',
      size: 3,
      range: 0,
      background: BuildingColor['农业'][7],
    },
    {
      name: '橄榄园',
      text: '橄榄园',
      size: 2,
      range: 0,
      background: BuildingColor['农业'][8],
    },
  ],
  工业: [
    {
      name: '陶瓦场',
      text: '陶瓦场',
      size: 2,
      range: 0,
      background: BuildingColor['工业'][0],
    },
    {
      name: '炼铜场',
      text: '炼铜场',
      size: 2,
      range: 0,
      background: BuildingColor['工业'][1],
    },
    {
      name: '塑像场',
      text: '塑像场',
      size: 2,
      range: 0,
      background: BuildingColor['工业'][2],
    },
    {
      name: '陶器场',
      text: '陶器场',
      size: 2,
      range: 0,
      background: BuildingColor['工业'][3],
    },
    {
      name: '纺织厂',
      text: '纺织厂',
      size: 2,
      range: 0,
      background: BuildingColor['工业'][4],
    },
    {
      name: '酒坊',
      text: '酒坊',
      size: 2,
      range: 0,
      background: BuildingColor['工业'][5],
    },
    {
      name: '奶酪场',
      text: '奶酪场',
      size: 2,
      range: 0,
      background: BuildingColor['工业'][6],
    },
    {
      name: '油坊',
      text: '油坊',
      size: 2,
      range: 0,
      background: BuildingColor['工业'][7],
    },
  ],
  商业: [
    {
      name: '粮食货摊',
      text: '粮',
      size: 1,
      range: 5,
      background: BuildingColor['商业'][0],
    },
    {
      name: '蔬菜货摊',
      text: '菜',
      size: 1,
      range: 5,
      background: BuildingColor['商业'][1],
    },
    {
      name: '水果货摊',
      text: '果',
      size: 1,
      range: 5,
      background: BuildingColor['商业'][2],
    },
    {
      name: '生肉货摊',
      text: '肉',
      size: 1,
      range: 5,
      background: BuildingColor['商业'][3],
    },
    {
      name: '鱼虾货摊',
      text: '鱼',
      size: 1,
      range: 5,
      background: BuildingColor['商业'][4],
    },
    {
      name: '陶器店',
      text: '陶',
      size: 1,
      range: 5,
      background: BuildingColor['商业'][5],
    },
    {
      name: '亚麻布店',
      text: '布',
      size: 1,
      range: 5,
      background: BuildingColor['商业'][6],
    },
    {
      name: '酒馆',
      text: '酒',
      size: 1,
      range: 5,
      background: BuildingColor['商业'][7],
    },
    {
      name: '羊毛货摊',
      text: '羊',
      size: 1,
      range: 5,
      background: BuildingColor['商业'][8],
    },
    {
      name: '奶酪货摊',
      text: '奶',
      size: 1,
      range: 5,
      background: BuildingColor['商业'][9],
    },
    {
      name: '橄榄油货摊',
      text: '橄',
      size: 1,
      range: 5,
      background: BuildingColor['商业'][10],
    },
  ],
  市政: [
    {
      name: '喷泉',
      text: '水',
      size: 1,
      range: 4,
      background: BuildingColor['市政']['水'],
    },
    {
      name: '消防局',
      text: '消',
      size: 1,
      range: 6,
      background: BuildingColor['市政']['防'],
    },
    {
      name: '维修所',
      text: '维',
      size: 1,
      range: 6,
      background: BuildingColor['市政']['防'],
    },
    {
      name: '瞭望台',
      text: '瞭',
      size: 1,
      range: 7,
      background: BuildingColor['市政']['防'],
    },
    {
      name: '诊所',
      text: '诊所',
      size: 2,
      range: 7,
      background: BuildingColor['市政']['防'],
    },
    {
      name: '粮仓',
      text: '粮仓',
      size: 2,
      range: 0,
      background: BuildingColor['市政']['粮'],
    },
    {
      name: '货栈',
      text: '货栈',
      size: 3,
      range: 0,
      background: BuildingColor['市政']['货'],
    },
    {
      name: '宫殿',
      text: '宫殿',
      size: 4,
      range: 0,
      background: BuildingColor['市政']['殿'],
    },
    {
      name: '议会厅',
      text: '议会厅',
      size: 2,
      range: 6,
      background: BuildingColor['市政']['职'],
    },
    {
      name: '贸易站',
      text: '贸易站',
      size: 2,
      range: 0,
      background: BuildingColor['市政']['贸'],
    },
    {
      name: '税务局',
      text: '税',
      size: 1,
      range: 4,
      background: BuildingColor['市政']['税'],
    },
    {
      name: '风力磨坊',
      text: '磨',
      size: 1,
      range: 4,
      background: BuildingColor['市政']['磨'],
    },
    {
      name: '水车',
      text: '水车',
      size: 2,
      range: 4,
      background: BuildingColor['市政']['浇'],
    },
  ],
  文化: [
    {
      name: '剧场',
      text: '剧场',
      size: 2,
      range: 6,
      background: BuildingColor['文化'][0],
    },
    {
      name: '露天体育场',
      text: '露天体育场',
      size: 6,
      range: 10,
      background: BuildingColor['文化'][1],
    },
    {
      name: '大学',
      text: '大学',
      size: 5,
      range: 8,
      background: BuildingColor['文化'][2],
    },
    {
      name: '图书馆',
      text: '图书馆',
      size: 5,
      range: 8,
      background: BuildingColor['文化'][3],
    },
  ],
  宗教: [
    {
      name: '小神殿',
      text: '小神殿',
      size: 2,
      range: 5,
      background: BuildingColor['宗教'][0],
    },
    {
      name: '中神殿',
      text: '中神殿',
      size: 3,
      range: 7,
      background: BuildingColor['宗教'][1],
    },
    {
      name: '大神殿',
      text: '大神殿',
      size: 8,
      range: 9,
      background: BuildingColor['宗教'][2],
    },
  ],
  军事: [
    {
      name: '步兵兵营',
      text: '步兵',
      size: 2,
      range: 0,
      background: BuildingColor['军事'][0],
    },
    {
      name: '射手兵营',
      text: '射手',
      size: 2,
      range: 0,
      background: BuildingColor['军事'][1],
    },
    {
      name: '骑兵兵营',
      text: '骑兵',
      size: 2,
      range: 0,
      background: BuildingColor['军事'][2],
    },
    {
      name: '祭坛',
      text: '祭坛',
      size: 2,
      range: 0,
      background: BuildingColor['军事'][3],
    },
    {
      name: '武器铺',
      text: '武器铺',
      size: 2,
      range: 0,
      background: BuildingColor['军事'][4],
    },
    {
      name: '马厩',
      text: '马厩',
      size: 2,
      range: 0,
      background: BuildingColor['军事'][5],
    },
  ],
  美化: [
    {
      name: '树',
      text: '树',
      size: 1,
      range: 0,
      background: BuildingColor['美化']['树'],
    },
  ],
  奇迹: [
    {
      name: '特洛伊木马',
      text: '特洛伊木马',
      size: 3,
      range: 0,
      background: BuildingColor['奇迹'][0],
    },
    {
      name: '宙斯神像',
      text: '宙斯神像',
      size: 4,
      range: 0,
      background: BuildingColor['奇迹'][1],
    },
    {
      name: '罗德岛巨像',
      text: '罗德岛巨像',
      size: 4,
      range: 0,
      background: BuildingColor['奇迹'][2],
    },
    {
      name: '摩索拉斯基陵墓',
      text: '摩索拉斯基陵墓',
      size: 5,
      range: 0,
      background: BuildingColor['奇迹'][3],
    },
  ],
};
